version: 2.1
jobs:
  run_Jmeter:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: apk update
          command: apk update
      - run:
          name:  install git 
          command: apk add git
      - run:
          name: Install plugin
          command: |
            wget http://central.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.8/jmeter-plugins-manager-1.8.jar
            mv ./jmeter-plugins-manager-1.8.jar ${JMETER_HOME}/lib/ext
            wget http://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar
            mv ./cmdrunner-2.2.jar ${JMETER_HOME}/lib
            java -cp ${JMETER_HOME}/lib/ext/jmeter-plugins-manager-1.8.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
            ${JMETER_HOME}/bin/PluginsManagerCMD.sh install-all-except 
      - run:
          name:  Run Jmeter
          command: |
            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo Commit message :  $COMMIT_MESSAGE
            export testlink="$(echo $COMMIT_MESSAGE | awk '{print $2}')"
            export qano="$(echo -n $COMMIT_MESSAGE | grep -o '[^ ]\+$')"
            echo Testlink : $testlink
            echo Qano : $qano
            mkdir results_folder1
            jmeter -n -t JmxFile/dryRun_derivcom.jmx -l jmeter_report.csv -e -o results_folder1
      - store_artifacts:
          path: results_folder1


  
workflows:
  version: 2.1
  run_jmeter:
    jobs:
      - run_Jmeter
  nightly_10am:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_Jmeter 
  nightly_2pm:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_Jmeter
  nightly_6pm:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_Jmeter    