version: 2.1

default: &default
  docker:
    - image: justb4/jmeter:latest
  working_directory: ~/repo

alias:
  - &app_get
    run:
     name: install apt get
     command: 'apt-get install'

  - &git_install
    run:
     name:  install git
     command: 'apt-get -y install git'
  
  - &create_dir
    run:
     name:  Create directory for reports
     command: |
        mkdir results_folder

  - &runTest
    run:
     name:  Run JmeterTest
     command: |
        jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder

jobs:
  CircleCI_Jmeter:
    <<: *default
    parallelism: 1
    steps:
      - checkout
      - *create_dir
      - *runTest
      - store_test_results:
          path:  /results_folder
      - store_artifacts:
          path:  /results_folder
 
workflows:
  version: 2.1
  workflow:
    jobs:
    - CircleCI_Jmeter
        