version: 2.1

jobs:
  CircleCI_Jmeter:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: Make Result Directory
          command: mkdir results_folder
      - run:
          name: Run Test
          command: |
          COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
          console.log($COMMIT_MESSAGE)
          jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder
      - store_artifacts:
          path: results_folder


workflows:
  CircleCI_Jmeter_workflow:
    jobs:
      - CircleCI_Jmeter
