version: 2.1
jobs:
  Install_Git:
    working_directory: ~/repo
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: apk update
          command: apk update
      - run:
          name:  install git 
          command: apk add git
      - run:
          name:  Get QA No. and Testlink message
          command: |
            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo this is the commit message $COMMIT_MESSAGE
            QANo='$(echo -n $COMMIT_MESSAGE | grep -o '[^ ]\+$')'
            testLink='$(echo $COMMIT_MESSAGE | awk '{print $2}')'
      - run: 
          name: mkdir -p workspace
          command: mkdir -p workspace
      - run: 
          name: Put QA No is workspace 
          command: |
            echo "export QABox=$QANo" >> workspace/new-env-vars
            cat workspace/new-env-vars >> $BASH_ENV
      - run: 
          name: Run Jmx file
          command: |
            jmeter -n -t JmxFile/DerivPage$testLink.jmx -l jmeter_report.csv -e -o results_folder
      - store_artifacts:
          path: results_folder

  # Jmeter_Report:
  #   working_directory: /tmp/cci-test
  #   docker:
  #     - image: justb4/jmeter:latest
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: /tmp/cci-test/workspace
  #     - run: cat workspace/new-env-vars >> $BASH_ENV
  #     - run: echo "This is running in the second job"
  #     - run: echo $QABox
  #     - run: echo $TestLink
  #     - run:
  #         name:  Run JmeterTest
  #         command: jmeter -n -t JmxFile/DerivPage$TestLink.jmx -l jmeter_report.csv -e -o results_folder
  #     - store_artifacts:
  #         path: results_folder
  #     - persist_to_workspace:
  #         root: workspace
  #         paths:
  #             - new-env-vars
  
workflows:
  version: 2.1
  example_jobs:
    jobs:
      - Install_Git
      # - Jmeter_Report:
      #     requires:
      #       - Install_Gits