version: 2.1

jobs:
  CircleCI_Jmeter:
    docker:
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run:
          name: indtall apt-get
          command: sudo apt-get update
      - run:
          name: install git 
          command: sudo apt-get -y install git
      - store_artifacts:
      - run:
          name: echo commit 
          command: |
            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            QANo="$(echo -n $COMMIT_MESSAGE | grep -o '[^ ]\+$')"
            echo $QANo

jobs:
  CircleCI_Jmeter:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: Make Result Directory
          command: mkdir results_folder 
      - run:
          name: Run Test
          command: |
            echo "test echo"
            jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder
      - store_artifacts:
          path: results_folder


workflows:
  CircleCI_Jmeter_workflow:
    jobs:
      - CircleCI_Jmeter
