version: 2.1
jobs:
  Job_run_Jmeter1:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: apk update
          command: apk update
      - run:
          name:  install git 
          command: apk add git
      - run:
          name:  Run Jmeter
          command: |
            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo Commit message :  $COMMIT_MESSAGE
            export testlink="$(echo $COMMIT_MESSAGE | awk '{print $2}')"
            export qano="$(echo -n $COMMIT_MESSAGE | grep -o '[^ ]\+$')"
            echo Testlink : $testlink
            echo Qano : $qano
            mkdir results_folder1
            jmeter -n -t JmxFile/Derivcom.jmx -l jmeter_report.csv -e -o results_folder1
      - store_artifacts:
          path: results_folder1
  
  Job_run_Jmeter2:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: apk update
          command: apk update
      - run:
          name:  install git 
          command: apk add git
      - run:
          name:  Run Jmeter
          command: |
            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo Commit message :  $COMMIT_MESSAGE
            export testlink="$(echo $COMMIT_MESSAGE | awk '{print $2}')"
            export qano="$(echo -n $COMMIT_MESSAGE | grep -o '[^ ]\+$')"
            echo Testlink : $testlink
            echo Qano : $qano
            mkdir results_folder2
            jmeter -n -t JmxFile/Derivcom.jmx -l jmeter_report.csv -e -o results_folder2
      - store_artifacts:
          path: results_folder2

  
workflows:
  version: 2.1
  run_jmeter1:
    jobs:
    - run_Jmeter1
  nightly_10am:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_Jmeter1 
  nightly_2pm:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_Jmeter1
  nightly_6pm:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_Jmeter1  