version: 2.1

default: &default
  docker:
    - image: ustb4/jmeter:latest
  working_directory: ~/repo

alias:
  - &app_get
    run:
     name: install apt get
     command: 'sudo apt-get update'

  - &git_install
    run:
     name:  install git
     command: 'sudo apt-get -y install git'
  
  - &create_dir
    run:
     name:  Create directory for reports
     command: |
        sudo mkdir results_folder

  - &CircleCI_Jmeter
    run:
     name:  Run Jmeter Test
     command: |
        jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder

jobs:
  CircleCI_Jmeter:
    working_directory: ~/repo
    parallelism: 1
    steps:
      - checkout
      - *app_get
      - *git_install
      - *create_dir
      - *CircleCI_Jmeter
      - store_test_results:
          path:  /results_folder
      - store_artifacts:
          path:  /results_folder
 
workflows:
  version: 2.1
  workflow:
    jobs:
    - CircleCI_Jmeter
        