version: 2.1

jobs:
  jmeter_staging:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: Create directory
          command: mkdir results
      - run:
          name: Install plugin
          command: |
            wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar
            mv ./cmdrunner-2.3.jar ${JMETER_HOME}/lib
            wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.8/jmeter-plugins-manager-1.8.jar
            mv ./jmeter-plugins-manager-1.8.jar ${JMETER_HOME}/lib/ext
            java -cp ${JMETER_HOME}/lib/ext/jmeter-plugins-manager-1.8.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
            PluginsManagerCMD.sh install jpgc-casutg,jpgc-tst
      - run:
          name:  Run JMeter
          command: |
            jmeter -n -t JmxFile/stg_dryRun_derivcom.jmx -l results/jmeter_report.csv -e -o results
      - store_artifacts:
          path: results
  
workflows:
  run_jmeter:
    jobs:
      - jmeter_staging
  nightly_10am:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - jmeter_staging 
  nightly_2pm:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - jmeter_staging
  nightly_6pm:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - jmeter_staging    