version: 2.1
git: ganta/git@1.2.0


default: &default
  docker:
    - image: selenium/standalone-chrome
    - image: justb4/jmeter:latest
  working_directory: ~/repo

alias:
  - &app_get
    run:
     name: install apt get
     command: 'sudo apt-get update'

  - &git_install
    run:
     name:  install git
     command: 'sudo apt-get -y install git'
  
  - &fetch_commit
    run:
     name:  Get commit message
     command: |
      COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
      echo $COMMIT_MESSAGE

  - &create_dir
    run:
     name:  Create directory for reports
     command: |
        mkdir results_folder

  - &runTest
    run:
     name:  Run JmeterTest
     command: |
        jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder

jobs:
  CircleCI_Jmeter:
    <<: *default
    parallelism: 1
    steps:
      - checkout
      - *app_get
      - *git_install
      - *fetch_commit
      - *create_dir
      - *runTest
      - store_test_results:
          path:  results_folder
      - store_artifacts:
          path:  results_folder
 
workflows:
  version: 2.1
  workflow:
    jobs:
    - CircleCI_Jmeter
        