defaults: &defaults
  working_directory: /tmp/cci-test
version: 2.1
jobs:
  Install_Git:
    working_directory: /tmp/cci-test
    docker:
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run:
          name: install appt-get
          command: sudo apt-get update
      - run:
          name:  install git 
          command: sudo apt-get -y install git
      - run:
          name:  Get commit message
          command: |
            COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo "export QANo='$(echo -n $COMMIT_MESSAGE | grep -o '[^ ]\+$')'" >> $BASH_ENV
      - run: 
          name: mkdir -p workspace
          command: mkdir -p workspace
      - run: 
          name: Put data is workspace 
          command: |
            echo "export QABox=$QANo" >> workspace/new-env-vars
            cat workspace/new-env-vars >> $BASH_ENV
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars


  Jmeter_Report:
    working_directory: /tmp/cci-test
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "This is running in the second job"
      - run: ls -l
      - run: ls
      - run: echo ${QABox:-NULL}
      - run: ls -l
      - run: ls
      - run:
          name: Make Result Directory
          command: mkdir results_folder 
      - run:
          name:  Run JmeterTest
          command: jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder
      - store_artifacts:
          path: results_folder
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars
  
workflows:
  version: 2.1
  example_jobs:
    jobs:
      - Install_Git
      - Jmeter_Report:
          requires:
            - Install_Git


