version: 2.1

jobs:
  # Job one with a unique name
  say_hello:
    docker:
     - image: selenium/standalone-chrome
    steps:
      - run: echo "Say hello to YAML!"

  # Job two with a unique name
  say_goodbye:
    docker:
     - image: justb4/jmeter:latest
    steps:
      - checkout
      - run:
          name: Make Result Directory
          command: mkdir results_folder 
      - run:
          name:  Run JmeterTest
          command: jmeter -n -t JmxFile/DerivPage.jmx -l results_folder/jmeter_report.csv -e -o results_folder
      - store_artifacts:
          path: results_folder

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye