defaults: &defaults
  working_directory: /tmp/cci-test
version: 2.1
jobs:
  s1:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: pwd
      - run:
          name: set var
          command: echo "export BAZ=baz.`date +%Y%m%d.%H%M`" >> $BASH_ENV
      - run: echo "$BAZ"
      - run: mkdir -p workspace
      - run: echo "export FOO=foo.`date +%Y%m%d.%H%M%S`" >>workspace/new-env-vars
      - run: echo "export BOB=$BAZ" >> workspace/new-env-vars
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo ${FOO:-NULL}
      - run: echo ${BAZ:-NULL}
      - run: echo ${BOB:-NULL}
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars
  s2:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "This is running in the second job"
      - run: ls -l
      - run: echo ${FOO:-NULL}
      - run: echo ${BAZ:-NULL}
      - run: echo ${BOB:-NULL}
      - run: echo "export SUE=sue.`date +%Y%m%d.%H%M%S`" >>workspace/new-env-vars
  s3:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "This is running in the second job"
      - run: ls -l
      - run: echo ${FOO:-NULL}
      - run: echo ${BAZ:-NULL}
      - run: echo ${BOB:-NULL}
      - run: echo ${SUE:-NULL}
  s4:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "This is running in the second job"
      - run: ls -l
      - run: echo ${FOO:-NULL}
      - run: echo ${BAZ:-NULL}
      - run: echo ${BOB:-NULL}
      - run: echo ${SUE:-NULL}
      - run: echo "export SUE=sue.`date +%Y%m%d.%H%M%S`" >>workspace/new-env-vars
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars
  s5:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "This is running in the second job"
      - run: ls -l
      - run: echo ${FOO:-NULL}
      - run: echo ${BAZ:-NULL}
      - run: echo ${BOB:-NULL}
      - run: echo ${SUE:-NULL}
workflows:
  version: 2
  example_jobs:
    jobs:
      - s1
      - s2:
          requires:
            - s1
      - s3:
          requires:
            - s2
      - s4:
          requires:
            - s3
      - s5:
          requires:
            - s4